import Head from "next/head";

// Import Components
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Projects from "@/components/Projects";
import About from "@/components/About";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <div className="desktop-snap">
      <Head>
        <title>Gamisonia Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Hero />

      <div className="desktop-snap-child">
        <Projects />
      </div>
      <div className="desktop-snap-child">
        <About />
      </div>
      <div className="desktop-snap-child">
        <Contact />
      </div>

      <Footer />
    </div>
  );
}
