import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Second() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Second Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Second Page Design
    </div>
  );
}
